fix: fix sending output to notification
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

diff --git a/.github/workflows/release-send-mattermost-announcement.yml b/.github/workflows/release-send-mattermost-announcement.yml
--- a/.github/workflows/release-send-mattermost-announcement.yml
+++ b/.github/workflows/release-send-mattermost-announcement.yml
@@ -19,10 +19,10 @@ jobs:
       run: |
         BRANCH=${{ github.event.inputs.version }}
         BRANCH=${BRANCH%.*}.x
-
         SCRIPT_OUTPUT=$(./utils/check-branches.sh "${BRANCH}")
-        if [[ $? == 1 ]]; then
-          echo "${SCRIPT_OUTPUT}" >> ${GITHUB_OUTPUT}
+        if [[ "${SCRIPT_OUTPUT}" == *"[ERROR]"* ]]; then
+          #TODO find a working solution to output multiline text in the next step
+          exit 1
         fi
     - name: Create success message
       run: |
@@ -32,7 +32,7 @@ jobs:
     - name: Create failure message
       if: ${{ failure() }}
       run: |
-        echo "{\"text\":\":che-logo: Che ${{ github.event.inputs.version }} release final checks have failed:\n\n ${{join(steps.check.outputs.*, '\n')}}.\"}" > mattermost.json
+        echo "{\"text\":\":che-logo: Che ${{ github.event.inputs.version }} release final checks have failed:\n\n failed: https://github.com/eclipse-che/che-release/actions/workflows/release-send-mattermost-announcement.yml '\n')}}.\"}" > mattermost.json
     - name: Send message
       if: ${{ success() }} || ${{ failure() }}
       uses: mattermost/action-mattermost-notify@1.1.0
